apiVersion: batch/v2alpha1
kind: CronJob
metadata:
    name: s3-job
spec:
  schedule: "15 * * * *"
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec: 
          containers:
          - name: s3-job
            image: 092896522805.dkr.ecr.us-west-2.amazonaws.com/s3-backend-job:latest
            imagePullPolicy: Always
            args: ["datalens-logs" , "prod"]
