apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: s3-job
spec:
  replicas: 1
  template:
    metadata:
      labels: 
        app: s3-job
      annotations:
        kube2iam.beta.nordstrom.net/role: arn:aws:iam::092896522805:role/datalens/k8s/platform
    spec: 
      containers:
      - name: s3-job
        image: 543369334115.dkr.ecr.us-west-2.amazonaws.com/s3-backend-job:latest
        #command: ["dotnet"]
        #args: ["--help"]
        #command: ["sleep"]
        #args: ["30000"]
        #command: ["dotnet run --project S3ClassLib/S3ClassLib.csproj"]
        args: ["datalens-logs",  "prod"]

        


        
